export interface CountryCode {
  iso2: string
  dial: string
  name: string
  maxDigits?: number
}

export const COUNTRY_CODES: CountryCode[] = [
  { iso2: 'AR', dial: '+54',  name: 'Argentina',           maxDigits: 10 },
  { iso2: 'BR', dial: '+55',  name: 'Brasil',              maxDigits: 11 },
  { iso2: 'CL', dial: '+56',  name: 'Chile',               maxDigits: 9  },
  { iso2: 'UY', dial: '+598', name: 'Uruguay',             maxDigits: 8  },
  { iso2: 'PY', dial: '+595', name: 'Paraguay',            maxDigits: 9  },
  { iso2: 'BO', dial: '+591', name: 'Bolivia',             maxDigits: 8  },
  { iso2: 'PE', dial: '+51',  name: 'Perú',                maxDigits: 9  },
  { iso2: 'EC', dial: '+593', name: 'Ecuador',             maxDigits: 9  },
  { iso2: 'CO', dial: '+57',  name: 'Colombia',            maxDigits: 10 },
  { iso2: 'VE', dial: '+58',  name: 'Venezuela',           maxDigits: 10 },
  { iso2: 'MX', dial: '+52',  name: 'México',              maxDigits: 10 },
  { iso2: 'PA', dial: '+507', name: 'Panamá',              maxDigits: 8  },
  { iso2: 'CR', dial: '+506', name: 'Costa Rica',          maxDigits: 8  },
  { iso2: 'NI', dial: '+505', name: 'Nicaragua',           maxDigits: 8  },
  { iso2: 'HN', dial: '+504', name: 'Honduras',            maxDigits: 8  },
  { iso2: 'SV', dial: '+503', name: 'El Salvador',         maxDigits: 8  },
  { iso2: 'GT', dial: '+502', name: 'Guatemala',           maxDigits: 8  },
  { iso2: 'DO', dial: '+1',   name: 'República Dominicana', maxDigits: 10 },
  { iso2: 'CU', dial: '+53',  name: 'Cuba',                maxDigits: 8  },
  { iso2: 'PR', dial: '+1',   name: 'Puerto Rico',         maxDigits: 10 },

  { iso2: 'US', dial: '+1',   name: 'Estados Unidos',      maxDigits: 10 },
  { iso2: 'CA', dial: '+1',   name: 'Canadá',              maxDigits: 10 },
  { iso2: 'ES', dial: '+34',  name: 'España',              maxDigits: 9  },
  { iso2: 'PT', dial: '+351', name: 'Portugal',            maxDigits: 9  },

  { iso2: 'DE', dial: '+49',  name: 'Alemania',            maxDigits: 11 },
  { iso2: 'AD', dial: '+376', name: 'Andorra' },
  { iso2: 'AT', dial: '+43',  name: 'Austria' },
  { iso2: 'BE', dial: '+32',  name: 'Bélgica' },
  { iso2: 'BG', dial: '+359', name: 'Bulgaria' },
  { iso2: 'CY', dial: '+357', name: 'Chipre' },
  { iso2: 'HR', dial: '+385', name: 'Croacia' },
  { iso2: 'DK', dial: '+45',  name: 'Dinamarca' },
  { iso2: 'SK', dial: '+421', name: 'Eslovaquia' },
  { iso2: 'SI', dial: '+386', name: 'Eslovenia' },
  { iso2: 'EE', dial: '+372', name: 'Estonia' },
  { iso2: 'FI', dial: '+358', name: 'Finlandia' },
  { iso2: 'FR', dial: '+33',  name: 'Francia',             maxDigits: 9 },
  { iso2: 'GR', dial: '+30',  name: 'Grecia',              maxDigits: 10 },
  { iso2: 'HU', dial: '+36',  name: 'Hungría' },
  { iso2: 'IE', dial: '+353', name: 'Irlanda' },
  { iso2: 'IS', dial: '+354', name: 'Islandia' },
  { iso2: 'IT', dial: '+39',  name: 'Italia',              maxDigits: 10 },
  { iso2: 'LV', dial: '+371', name: 'Letonia' },
  { iso2: 'LI', dial: '+423', name: 'Liechtenstein' },
  { iso2: 'LT', dial: '+370', name: 'Lituania' },
  { iso2: 'LU', dial: '+352', name: 'Luxemburgo' },
  { iso2: 'MT', dial: '+356', name: 'Malta' },
  { iso2: 'MD', dial: '+373', name: 'Moldavia' },
  { iso2: 'MC', dial: '+377', name: 'Mónaco' },
  { iso2: 'NO', dial: '+47',  name: 'Noruega' },
  { iso2: 'NL', dial: '+31',  name: 'Países Bajos' },
  { iso2: 'PL', dial: '+48',  name: 'Polonia' },
  { iso2: 'GB', dial: '+44',  name: 'Reino Unido',         maxDigits: 10 },
  { iso2: 'CZ', dial: '+420', name: 'República Checa' },
  { iso2: 'RO', dial: '+40',  name: 'Rumania' },
  { iso2: 'RU', dial: '+7',   name: 'Rusia',               maxDigits: 10 },
  { iso2: 'SM', dial: '+378', name: 'San Marino' },
  { iso2: 'RS', dial: '+381', name: 'Serbia' },
  { iso2: 'SE', dial: '+46',  name: 'Suecia' },
  { iso2: 'CH', dial: '+41',  name: 'Suiza' },
  { iso2: 'TR', dial: '+90',  name: 'Turquía' },
  { iso2: 'UA', dial: '+380', name: 'Ucrania' },
  { iso2: 'VA', dial: '+379', name: 'Vaticano' },

  { iso2: 'AU', dial: '+61',  name: 'Australia' },
  { iso2: 'BD', dial: '+880', name: 'Bangladés' },
  { iso2: 'CN', dial: '+86',  name: 'China',               maxDigits: 11 },
  { iso2: 'KR', dial: '+82',  name: 'Corea del Sur' },
  { iso2: 'AE', dial: '+971', name: 'Emiratos Árabes Unidos' },
  { iso2: 'PH', dial: '+63',  name: 'Filipinas' },
  { iso2: 'HK', dial: '+852', name: 'Hong Kong' },
  { iso2: 'IN', dial: '+91',  name: 'India',               maxDigits: 10 },
  { iso2: 'ID', dial: '+62',  name: 'Indonesia' },
  { iso2: 'IL', dial: '+972', name: 'Israel' },
  { iso2: 'JP', dial: '+81',  name: 'Japón' },
  { iso2: 'JO', dial: '+962', name: 'Jordania' },
  { iso2: 'KW', dial: '+965', name: 'Kuwait' },
  { iso2: 'LB', dial: '+961', name: 'Líbano' },
  { iso2: 'MY', dial: '+60',  name: 'Malasia' },
  { iso2: 'NZ', dial: '+64',  name: 'Nueva Zelanda' },
  { iso2: 'PK', dial: '+92',  name: 'Pakistán' },
  { iso2: 'QA', dial: '+974', name: 'Qatar' },
  { iso2: 'SA', dial: '+966', name: 'Arabia Saudita' },
  { iso2: 'SG', dial: '+65',  name: 'Singapur' },
  { iso2: 'TW', dial: '+886', name: 'Taiwán' },
  { iso2: 'TH', dial: '+66',  name: 'Tailandia' },
  { iso2: 'VN', dial: '+84',  name: 'Vietnam' },

  { iso2: 'ZA', dial: '+27',  name: 'Sudáfrica' },
  { iso2: 'AO', dial: '+244', name: 'Angola' },
  { iso2: 'DZ', dial: '+213', name: 'Argelia' },
  { iso2: 'EG', dial: '+20',  name: 'Egipto' },
  { iso2: 'ET', dial: '+251', name: 'Etiopía' },
  { iso2: 'GH', dial: '+233', name: 'Ghana' },
  { iso2: 'KE', dial: '+254', name: 'Kenia' },
  { iso2: 'MA', dial: '+212', name: 'Marruecos' },
  { iso2: 'NG', dial: '+234', name: 'Nigeria' },
  { iso2: 'SN', dial: '+221', name: 'Senegal' },
  { iso2: 'TN', dial: '+216', name: 'Túnez' },

  { iso2: 'AL', dial: '+355', name: 'Albania' },
  { iso2: 'AM', dial: '+374', name: 'Armenia' },
  { iso2: 'AZ', dial: '+994', name: 'Azerbaiyán' },
  { iso2: 'BH', dial: '+973', name: 'Baréin' },
  { iso2: 'BY', dial: '+375', name: 'Bielorrusia' },
  { iso2: 'BA', dial: '+387', name: 'Bosnia y Herzegovina' },
  { iso2: 'GE', dial: '+995', name: 'Georgia' },
  { iso2: 'KZ', dial: '+7',   name: 'Kazajistán' },
  { iso2: 'MK', dial: '+389', name: 'Macedonia del Norte' },
  { iso2: 'ME', dial: '+382', name: 'Montenegro' },
  { iso2: 'OM', dial: '+968', name: 'Omán' },
]

export function findByDial(dial: string): CountryCode | undefined {
  return COUNTRY_CODES.find(c => c.dial === dial)
}

export function findByIso2(iso2: string): CountryCode | undefined {
  return COUNTRY_CODES.find(c => c.iso2.toUpperCase() === iso2.toUpperCase())
}

export const DEFAULT_COUNTRY: CountryCode = COUNTRY_CODES[0]
