export const RESERVED_SLUGS: ReadonlySet<string> = new Set([
  'auth',
  'ingresar',
  'login',
  'registro',
  'register',
  'recuperar',
  'admin',
  'dashboard',
  'publicar',
  'pagos',
  'planes',
  'contacto',
  'faq',
  'denuncias',
  'blocked',
  'terminos',
  'privacidad',
  'blog',
  'foro',
  'perfil',
  // /home is the canonical country-feed landing (rewritten to the country route).
  'home',
  'argentina',
  'chile',
  'brasil',
  'brazil',
  'mexico',
  'uruguay',
  'colombia',
  'api',
  'www',
  'sitemap.xml',
  'robots.txt',
  'favicon.ico',
  'sentry-example-page',
  'hogar-reparaciones',
  'clases-particulares',
  'belleza-bienestar',
  'eventos-fotografia',
  'tecnologia',
  'salud',
  'profesionales',
])

export function isReservedSlug(slug: string): boolean {
  return RESERVED_SLUGS.has(slug.toLowerCase().trim())
}
