-- ══════════════════════════════════════════════════════════════════════════
-- Boost purchase with credits
--
-- The boost schema already existed (posts.is_boosted / boost_ends_at + the
-- feed order); what was missing was the PURCHASE flow. Model: boost is paid
-- with CREDITS from the balance (no checkout), server-authoritative:
--
--   • `boost_purchases`: one row per purchase, with a UNIQUE
--     `idempotency_key` (generated by the client when the modal opens) as
--     the replay anchor — the same claim pattern as apply_payment_activation.
--   • `purchase_post_boost()`: validates owner+status, claims the key, debits
--     credits with a balance guard, stamps/extends boost_ends_at and records
--     the debit in the ledger — all in one transaction.
--   • Trigger guard: is_boosted/boost_ends_at/is_pinned/pin_ends_at become
--     server-managed columns. Without this, the posts_update policy would let
--     the owner flip is_boosted for free from the client and the purchase
--     would be decorative. Only service_role (and postgres: migrations/SQL
--     editor) can change them.
--
-- Idempotent: re-applying this migration is a no-op.
-- ══════════════════════════════════════════════════════════════════════════

-- ── Boost purchases table ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS boost_purchases (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Idempotency anchor: the client generates a UUID per purchase attempt;
  -- a replay (double-click, network retry) matches here and doesn't charge twice.
  idempotency_key  TEXT NOT NULL UNIQUE,
  post_id          UUID NOT NULL,
  user_id          UUID NOT NULL,
  credits_spent    INT  NOT NULL CHECK (credits_spent >= 0),
  duration_days    INT  NOT NULL CHECK (duration_days > 0),
  -- Boost end resulting from THIS purchase (audit; the live one lives in posts).
  boost_ends_at    TIMESTAMPTZ NOT NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_boost_purchases_user_id ON boost_purchases (user_id);
CREATE INDEX IF NOT EXISTS idx_boost_purchases_post_id ON boost_purchases (post_id);

-- RLS: a user sees their purchases; an admin sees all. Writes only via
-- service role (the RPC) — no INSERT/UPDATE policies. public.is_admin() =
-- SECURITY DEFINER helper (migration fix_profiles_policy_recursion).
ALTER TABLE boost_purchases ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS boost_purchases_select_own_or_admin ON boost_purchases;
CREATE POLICY boost_purchases_select_own_or_admin ON boost_purchases
  FOR SELECT TO authenticated USING (
    user_id = auth.uid() OR public.is_admin()
  );

GRANT SELECT ON boost_purchases TO authenticated;

-- ── Guard: paid-placement columns are server-managed ───────────────────────
-- posts_update (RLS) lets the owner update THEIR whole row; without this
-- trigger any owner could set is_boosted=true for free from the SDK.
-- IS DISTINCT FROM: only fires on a real CHANGE, so legitimate dashboard
-- updates (pause, edit) that resend the current value don't break.
-- current_user in PostgREST = the effective role ('authenticated'); inside a
-- SECURITY DEFINER function or in migrations it's 'postgres'.
CREATE OR REPLACE FUNCTION guard_paid_post_flags()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF current_user NOT IN ('service_role', 'postgres')
     AND (
       NEW.is_boosted    IS DISTINCT FROM OLD.is_boosted
       OR NEW.boost_ends_at IS DISTINCT FROM OLD.boost_ends_at
       OR NEW.is_pinned     IS DISTINCT FROM OLD.is_pinned
       OR NEW.pin_ends_at   IS DISTINCT FROM OLD.pin_ends_at
     )
  THEN
    RAISE EXCEPTION 'paid placement flags are server-managed'
      USING ERRCODE = 'insufficient_privilege';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS posts_guard_paid_flags ON posts;
CREATE TRIGGER posts_guard_paid_flags
  BEFORE UPDATE ON posts
  FOR EACH ROW EXECUTE FUNCTION guard_paid_post_flags();

-- ── Atomic purchase RPC ────────────────────────────────────────────────────
-- Returns: 'applied' | 'already-applied' | 'not-found' | 'not-owner'
--        | 'not-published' | 'insufficient-credits'
-- Cost and duration come from the server catalog (the route), never the body.
-- Buying with an active boost EXTENDS from the current end.
CREATE OR REPLACE FUNCTION purchase_post_boost(
  p_post_id         UUID,
  p_user_id         UUID,
  p_cost            INT,
  p_duration_days   INT,
  p_idempotency_key TEXT
) RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_owner  UUID;
  v_status TEXT;
  v_ends   TIMESTAMPTZ;
  v_days   INT := GREATEST(COALESCE(p_duration_days, 7), 1);
  v_cost   INT := GREATEST(COALESCE(p_cost, 0), 0);
BEGIN
  -- Lock the post: serializes concurrent purchases on the same post so two
  -- extensions don't read the same base boost_ends_at.
  SELECT user_id, status, GREATEST(COALESCE(boost_ends_at, now()), now())
    INTO v_owner, v_status, v_ends
    FROM posts WHERE id = p_post_id
    FOR UPDATE;

  IF NOT FOUND THEN
    RETURN 'not-found';
  END IF;
  IF v_owner IS DISTINCT FROM p_user_id THEN
    RETURN 'not-owner';
  END IF;
  IF v_status <> 'published' THEN
    RETURN 'not-published';
  END IF;

  v_ends := v_ends + make_interval(days => v_days);

  -- Idempotency claim: a replay of the same attempt matches the key and
  -- returns without charging again.
  INSERT INTO boost_purchases
    (idempotency_key, post_id, user_id, credits_spent, duration_days, boost_ends_at)
  VALUES
    (p_idempotency_key, p_post_id, p_user_id, v_cost, v_days, v_ends)
  ON CONFLICT (idempotency_key) DO NOTHING;

  IF NOT FOUND THEN
    RETURN 'already-applied';
  END IF;

  -- Debit with a balance guard in the same UPDATE (no read-modify-write).
  UPDATE profiles
     SET credits = credits - v_cost
   WHERE id = p_user_id AND credits >= v_cost;

  IF NOT FOUND THEN
    -- No balance: release the claim so a later attempt (after buying
    -- credits) can reuse the same key.
    DELETE FROM boost_purchases WHERE idempotency_key = p_idempotency_key;
    RETURN 'insufficient-credits';
  END IF;

  UPDATE posts
     SET is_boosted = true, boost_ends_at = v_ends
   WHERE id = p_post_id;

  INSERT INTO credit_transactions (user_id, amount, reason, reference)
  VALUES (p_user_id, -v_cost, 'boost_purchase', p_post_id::text);

  RETURN 'applied';
END;
$$;

-- Only the server-side API (service role) can purchase; nothing client-side.
REVOKE ALL ON FUNCTION purchase_post_boost(UUID, UUID, INT, INT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION purchase_post_boost(UUID, UUID, INT, INT, TEXT) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION purchase_post_boost(UUID, UUID, INT, INT, TEXT) TO service_role;
